# Generated by Django 5.2 on 2025-04-22 00:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('num_tel', models.CharField(max_length=20)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(blank=True, choices=[('client', 'Client'), ('pharmacie', 'Pharmacie'), ('medecin', 'Medecin'), ('livreur', 'Livreur'), ('admin', 'Admin')], max_length=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('specialite_medicale', models.CharField(blank=True, max_length=100, null=True)),
                ('agrement', models.FileField(blank=True, null=True, upload_to='doctor_docs/')),
                ('addresse', models.CharField(default='Non spécifiée', max_length=255)),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='doctor_stamps/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='doctor_signatures/')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('photo_de_profile', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('nom_pharmacie', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_proprietaire', models.CharField(blank=True, max_length=255, null=True)),
                ('registre_commerce', models.FileField(blank=True, null=True, upload_to='pharmacy_docs/')),
                ('localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('heure_ouverture', models.TimeField(blank=True, null=True)),
                ('heure_fermeture', models.TimeField(blank=True, null=True)),
                ('offre_livraison', models.BooleanField(default=False)),
                ('lien_reseau_sociaux', models.URLField(blank=True, null=True)),
                ('invitation_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('sexe', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personne', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite_medicale', models.CharField(max_length=100)),
                ('agrement', models.FileField(upload_to='doctor_docs/')),
                ('addresse', models.CharField(max_length=255)),
                ('cachet', models.ImageField(blank=True, null=True, upload_to='doctor_stamps/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='doctor_signatures/')),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medecin', to='accounts.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_de_profile', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('sexe', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, null=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='accounts.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pharmacie', models.CharField(max_length=255)),
                ('nom_proprietaire', models.CharField(max_length=255)),
                ('registre_commerce', models.FileField(upload_to='pharmacy_docs/')),
                ('localisation', models.CharField(max_length=255)),
                ('heure_ouverture', models.TimeField()),
                ('heure_fermeture', models.TimeField()),
                ('offre_livraison', models.BooleanField(default=False)),
                ('lien_reseau_sociaux', models.URLField(blank=True, null=True)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacie', to='accounts.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponibilite', models.BooleanField(default=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur', to='accounts.personne')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacie')),
            ],
        ),
    ]
