# Generated by Django 5.2 on 2025-04-18 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='sexe',
        ),
        migrations.AddField(
            model_name='client',
            name='photo_de_profile',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/'),
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='addresse',
            field=models.CharField(default='Non spécifiée', max_length=255),
        ),
        migrations.AddField(
            model_name='personne',
            name='agrement',
            field=models.FileField(blank=True, null=True, upload_to='doctor_docs/'),
        ),
        migrations.AddField(
            model_name='personne',
            name='cachet',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_stamps/'),
        ),
        migrations.AddField(
            model_name='personne',
            name='heure_fermeture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='heure_ouverture',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='lien_reseau_sociaux',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='localisation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='nom_pharmacie',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='nom_proprietaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personne',
            name='offre_livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personne',
            name='registre_commerce',
            field=models.FileField(blank=True, null=True, upload_to='pharmacy_docs/'),
        ),
        migrations.AddField(
            model_name='personne',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_signatures/'),
        ),
        migrations.AddField(
            model_name='personne',
            name='specialite_medicale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='invitation_token',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='personne',
            name='photo_de_profile',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/'),
        ),
    ]
