# Generated by Django 5.2 on 2025-04-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_personne_sexe_client_photo_de_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='sexe',
            field=models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, null=True),
        ),
    ]
