# Generated by Django 5.2 on 2025-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_personne_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
