# Generated by Django 5.2 on 2025-04-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_personne_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
