# Generated by Django 5.2 on 2025-04-24 17:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_personne_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='addresse',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='agrement',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='cachet',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='heure_fermeture',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='heure_ouverture',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='invitation_token',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='lien_reseau_sociaux',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='localisation',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='nom_pharmacie',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='nom_proprietaire',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='offre_livraison',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='photo_de_profile',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='registre_commerce',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='specialite_medicale',
        ),
        migrations.RemoveField(
            model_name='pharmacie',
            name='invitation_token',
        ),
        migrations.AddField(
            model_name='livreur',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo_de_profile',
            field=models.ImageField(default='', upload_to='client_profiles/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livreur',
            name='pharmacie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livreurs', to='accounts.pharmacie'),
        ),
    ]
