# Generated by Django 5.2 on 2025-04-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_client_sexe_remove_personne_addresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pharmacie', 'Pharmacie'), ('medecin', 'Medecin')], max_length=10)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_profile', to='accounts.personne')),
            ],
        ),
    ]
