# Generated by Django 5.2 on 2025-04-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_pendingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
