# Generated by Django 5.2 on 2025-04-25 19:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_pharmacie_latitude_pharmacie_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livreur',
            name='invitation_token',
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='invitation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
