# Generated by Django 5.2 on 2025-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_livreur_invitation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacie',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
