# Generated by Django 5.2 on 2025-05-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_pharmacie_latitude_alter_pharmacie_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('pharmacie', 'Pharmacie'), ('medecin', 'Medecin'), ('livreur', 'Livreur'), ('is_admin', 'Administrateur')], max_length=10, null=True),
        ),
    ]
