# Generated by Django 5.2 on 2025-04-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Produit sans nom', max_length=100)),
                ('description', models.TextField(default='Aucune description')),
                ('laboratoire', models.CharField(default='Laboratoire inconnu', max_length=100)),
                ('pays_de_fabrication', models.CharField(default='Pays inconnu', max_length=100)),
                ('notice', models.TextField(default='Notice non fournie')),
                ('avertissements', models.TextField(default='Aucun avertissement')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categorie', models.CharField(default='Aucune categorie', max_length=50)),
                ('type_produit', models.CharField(choices=[('medicament', 'Médicament'), ('parapharmaceutique', 'Produit Parapharmaceutique')], default='medicament', max_length=20)),
                ('dosage', models.CharField(default='Dosage inconnu', max_length=50)),
                ('prescription_obligatoire', models.BooleanField(default=False)),
                ('remboursement', models.BooleanField(default=False)),
                ('molecule_active', models.CharField(default='Molécule non précisée', max_length=100)),
                ('forme_pharmaceutique', models.CharField(default='Forme non précisée', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parapharmaceutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Produit sans nom', max_length=100)),
                ('description', models.TextField(default='Aucune description')),
                ('laboratoire', models.CharField(default='Laboratoire inconnu', max_length=100)),
                ('pays_de_fabrication', models.CharField(default='Pays inconnu', max_length=100)),
                ('notice', models.TextField(default='Notice non fournie')),
                ('avertissements', models.TextField(default='Aucun avertissement')),
                ('prix', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categorie', models.CharField(default='Aucune categorie', max_length=50)),
                ('type_produit', models.CharField(choices=[('medicament', 'Médicament'), ('parapharmaceutique', 'Produit Parapharmaceutique')], default='medicament', max_length=20)),
                ('usage', models.TextField(default='Usage non précisé')),
                ('marque', models.CharField(default='Marque non précisée', max_length=100)),
                ('evaluation', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
