# Generated by Django 5.2 on 2025-04-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='id_produit',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parapharmaceutique',
            name='id_produit',
            field=models.BigIntegerField(default=0),
        ),
    ]
