# Generated by Django 5.2 on 2025-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_medicament_id_produit_parapharmaceutique_id_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='nom',
            field=models.CharField(default='Produit sans nom', max_length=255),
        ),
        migrations.AlterField(
            model_name='parapharmaceutique',
            name='nom',
            field=models.CharField(default='Produit sans nom', max_length=255),
        ),
    ]
