# Generated by Django 5.2 on 2025-04-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_medicament_nom_alter_parapharmaceutique_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicament',
            name='id_produit',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='parapharmaceutique',
            name='id_produit',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
