# Generated by Django 5.2 on 2025-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_alter_medicament_id_produit_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.UniqueConstraint(fields=('id_produit', 'nom', 'description', 'laboratoire', 'pays_de_fabrication', 'notice', 'avertissements', 'prix', 'categorie', 'type_produit', 'dosage', 'prescription_obligatoire', 'remboursement', 'molecule_active', 'forme_pharmaceutique'), name='unique_medicament_complet'),
        ),
        migrations.AddConstraint(
            model_name='parapharmaceutique',
            constraint=models.UniqueConstraint(fields=('id_produit', 'nom', 'description', 'laboratoire', 'pays_de_fabrication', 'notice', 'avertissements', 'prix', 'categorie', 'type_produit', 'usage', 'marque', 'evaluation'), name='unique_parapharmaceutique_complet'),
        ),
    ]
