# Generated by Django 5.2 on 2025-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_medicament_unique_medicament_complet_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicament',
            name='unique_medicament_complet',
        ),
        migrations.AddField(
            model_name='medicament',
            name='type_medicament',
            field=models.CharField(choices=[('original', 'Original'), ('generique', 'Générique')], default='original', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='categorie',
            field=models.CharField(choices=[('Antalgiques', 'Antalgiques'), ('Antibiotiques', 'Antibiotiques'), ('Anti-inflammatoires', 'Anti-inflammatoires'), ('Antispasmodiques', 'Antispasmodiques'), ('Antihistaminiques', 'Antihistaminiques'), ('Inhibiteurs de pompe à protons', 'Inhibiteurs de pompe à protons'), ('Antidiabétiques', 'Antidiabétiques'), ('Antihypertenseurs', 'Antihypertenseurs'), ('Antidépresseurs', 'Antidépresseurs'), ('Antiviraux', 'Antiviraux'), ('Antifongiques', 'Antifongiques'), ('Anticoagulants', 'Anticoagulants'), ('Vaccins', 'Vaccins')], default='Antalgiques', max_length=50),
        ),
        migrations.AlterField(
            model_name='parapharmaceutique',
            name='categorie',
            field=models.CharField(choices=[('Santé', 'Santé'), ('Hygiène', 'Hygiène'), ('Soins du visage et du corps', 'Soins du visage et du corps'), ('Capillaire', 'Capillaire'), ('Hygiène bucco-dentaire', 'Hygiène bucco-dentaire'), ('Bébé', 'Bébé')], default='Hygiène', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.UniqueConstraint(fields=('id_produit', 'nom', 'description', 'laboratoire', 'pays_de_fabrication', 'notice', 'avertissements', 'prix', 'categorie', 'type_produit', 'dosage', 'prescription_obligatoire', 'remboursement', 'molecule_active', 'forme_pharmaceutique', 'type_medicament'), name='unique_medicament_complet'),
        ),
    ]
