# Generated by Django 5.2 on 2025-04-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0006_remove_medicament_unique_medicament_complet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicament',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='produits/'),
        ),
        migrations.AddField(
            model_name='parapharmaceutique',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='produits/'),
        ),
    ]
